/* tslint:disable */
/* eslint-disable */
/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/courses-api';
export * from './api/districts-api';
export * from './api/resources-api';
export * from './api/schools-api';
export * from './api/sections-api';
export * from './api/terms-api';
export * from './api/users-api';

