/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  CoursesApi,
  DistrictsApi,
  ResourcesApi,
  SchoolsApi,
  SectionsApi,
  TermsApi,
  UsersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { CleverCustom } from "./client-custom";

export class Clever extends CleverCustom {
  readonly courses: CoursesApi;
  readonly districts: DistrictsApi;
  readonly resources: ResourcesApi;
  readonly schools: SchoolsApi;
  readonly sections: SectionsApi;
  readonly terms: TermsApi;
  readonly users: UsersApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.courses = new CoursesApi(configuration);
    this.districts = new DistrictsApi(configuration);
    this.resources = new ResourcesApi(configuration);
    this.schools = new SchoolsApi(configuration);
    this.sections = new SectionsApi(configuration);
    this.terms = new TermsApi(configuration);
    this.users = new UsersApi(configuration);
  }

}
