/* tslint:disable */
/* eslint-disable */
/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CourseResponse } from '../models';
// @ts-ignore
import { DistrictResponse } from '../models';
// @ts-ignore
import { NotFound } from '../models';
// @ts-ignore
import { ResourcesResponse } from '../models';
// @ts-ignore
import { SchoolResponse } from '../models';
// @ts-ignore
import { SectionResponse } from '../models';
// @ts-ignore
import { SectionsResponse } from '../models';
// @ts-ignore
import { TermResponse } from '../models';
// @ts-ignore
import { UsersResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * SectionsApi - axios parameter creator
 * @export
 */
export const SectionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the course for a section
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourse: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCourse', 'id', id)
            const localVarPath = `/sections/{id}/course`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections/{id}/course',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the district for a section
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDistrict: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getDistrict', 'id', id)
            const localVarPath = `/sections/{id}/district`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections/{id}/district',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of sections
         * @param {number} [limit] 
         * @param {string} [startingAfter] 
         * @param {string} [endingBefore] 
         * @param {'' | 'true' | 'false' | 'undefined'} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList: async (limit?: number, startingAfter?: string, endingBefore?: string, count?: '' | 'true' | 'false' | 'undefined', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (startingAfter !== undefined) {
                localVarQueryParameter['starting_after'] = startingAfter;
            }

            if (endingBefore !== undefined) {
                localVarQueryParameter['ending_before'] = endingBefore;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the resources for a section
         * @param {string} id 
         * @param {number} [limit] 
         * @param {string} [startingAfter] 
         * @param {string} [endingBefore] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResources: async (id: string, limit?: number, startingAfter?: string, endingBefore?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getResources', 'id', id)
            const localVarPath = `/sections/{id}/resources`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (startingAfter !== undefined) {
                localVarQueryParameter['starting_after'] = startingAfter;
            }

            if (endingBefore !== undefined) {
                localVarQueryParameter['ending_before'] = endingBefore;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections/{id}/resources',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the school for a section
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchool: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSchool', 'id', id)
            const localVarPath = `/sections/{id}/school`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections/{id}/school',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a specific section
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpecificSection: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSpecificSection', 'id', id)
            const localVarPath = `/sections/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the term for a section
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTerm: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTerm', 'id', id)
            const localVarPath = `/sections/{id}/term`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections/{id}/term',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the student and/or teacher users for a section
         * @param {string} id 
         * @param {'student' | 'teacher'} [role] 
         * @param {number} [limit] 
         * @param {string} [startingAfter] 
         * @param {string} [endingBefore] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers: async (id: string, role?: 'student' | 'teacher', limit?: number, startingAfter?: string, endingBefore?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getUsers', 'id', id)
            const localVarPath = `/sections/{id}/users`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth", [], configuration)
            if (role !== undefined) {
                localVarQueryParameter['role'] = role;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (startingAfter !== undefined) {
                localVarQueryParameter['starting_after'] = startingAfter;
            }

            if (endingBefore !== undefined) {
                localVarQueryParameter['ending_before'] = endingBefore;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/sections/{id}/users',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SectionsApi - functional programming interface
 * @export
 */
export const SectionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SectionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the course for a section
         * @param {SectionsApiGetCourseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCourse(requestParameters: SectionsApiGetCourseRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCourse(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the district for a section
         * @param {SectionsApiGetDistrictRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDistrict(requestParameters: SectionsApiGetDistrictRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DistrictResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDistrict(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a list of sections
         * @param {SectionsApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getList(requestParameters: SectionsApiGetListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SectionsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getList(requestParameters.limit, requestParameters.startingAfter, requestParameters.endingBefore, requestParameters.count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the resources for a section
         * @param {SectionsApiGetResourcesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getResources(requestParameters: SectionsApiGetResourcesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResourcesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getResources(requestParameters.id, requestParameters.limit, requestParameters.startingAfter, requestParameters.endingBefore, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the school for a section
         * @param {SectionsApiGetSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSchool(requestParameters: SectionsApiGetSchoolRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchoolResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSchool(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a specific section
         * @param {SectionsApiGetSpecificSectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpecificSection(requestParameters: SectionsApiGetSpecificSectionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSpecificSection(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the term for a section
         * @param {SectionsApiGetTermRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTerm(requestParameters: SectionsApiGetTermRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TermResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTerm(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the student and/or teacher users for a section
         * @param {SectionsApiGetUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsers(requestParameters: SectionsApiGetUsersRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsers(requestParameters.id, requestParameters.role, requestParameters.limit, requestParameters.startingAfter, requestParameters.endingBefore, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SectionsApi - factory interface
 * @export
 */
export const SectionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SectionsApiFp(configuration)
    return {
        /**
         * Returns the course for a section
         * @param {SectionsApiGetCourseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourse(requestParameters: SectionsApiGetCourseRequest, options?: AxiosRequestConfig): AxiosPromise<CourseResponse> {
            return localVarFp.getCourse(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the district for a section
         * @param {SectionsApiGetDistrictRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDistrict(requestParameters: SectionsApiGetDistrictRequest, options?: AxiosRequestConfig): AxiosPromise<DistrictResponse> {
            return localVarFp.getDistrict(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of sections
         * @param {SectionsApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList(requestParameters: SectionsApiGetListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<SectionsResponse> {
            return localVarFp.getList(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the resources for a section
         * @param {SectionsApiGetResourcesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResources(requestParameters: SectionsApiGetResourcesRequest, options?: AxiosRequestConfig): AxiosPromise<ResourcesResponse> {
            return localVarFp.getResources(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the school for a section
         * @param {SectionsApiGetSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchool(requestParameters: SectionsApiGetSchoolRequest, options?: AxiosRequestConfig): AxiosPromise<SchoolResponse> {
            return localVarFp.getSchool(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a specific section
         * @param {SectionsApiGetSpecificSectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpecificSection(requestParameters: SectionsApiGetSpecificSectionRequest, options?: AxiosRequestConfig): AxiosPromise<SectionResponse> {
            return localVarFp.getSpecificSection(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the term for a section
         * @param {SectionsApiGetTermRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTerm(requestParameters: SectionsApiGetTermRequest, options?: AxiosRequestConfig): AxiosPromise<TermResponse> {
            return localVarFp.getTerm(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the student and/or teacher users for a section
         * @param {SectionsApiGetUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers(requestParameters: SectionsApiGetUsersRequest, options?: AxiosRequestConfig): AxiosPromise<UsersResponse> {
            return localVarFp.getUsers(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCourse operation in SectionsApi.
 * @export
 * @interface SectionsApiGetCourseRequest
 */
export type SectionsApiGetCourseRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetCourse
    */
    readonly id: string
    
}

/**
 * Request parameters for getDistrict operation in SectionsApi.
 * @export
 * @interface SectionsApiGetDistrictRequest
 */
export type SectionsApiGetDistrictRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetDistrict
    */
    readonly id: string
    
}

/**
 * Request parameters for getList operation in SectionsApi.
 * @export
 * @interface SectionsApiGetListRequest
 */
export type SectionsApiGetListRequest = {
    
    /**
    * 
    * @type {number}
    * @memberof SectionsApiGetList
    */
    readonly limit?: number
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetList
    */
    readonly startingAfter?: string
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetList
    */
    readonly endingBefore?: string
    
    /**
    * 
    * @type {'' | 'true' | 'false' | 'undefined'}
    * @memberof SectionsApiGetList
    */
    readonly count?: '' | 'true' | 'false' | 'undefined'
    
}

/**
 * Request parameters for getResources operation in SectionsApi.
 * @export
 * @interface SectionsApiGetResourcesRequest
 */
export type SectionsApiGetResourcesRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetResources
    */
    readonly id: string
    
    /**
    * 
    * @type {number}
    * @memberof SectionsApiGetResources
    */
    readonly limit?: number
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetResources
    */
    readonly startingAfter?: string
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetResources
    */
    readonly endingBefore?: string
    
}

/**
 * Request parameters for getSchool operation in SectionsApi.
 * @export
 * @interface SectionsApiGetSchoolRequest
 */
export type SectionsApiGetSchoolRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetSchool
    */
    readonly id: string
    
}

/**
 * Request parameters for getSpecificSection operation in SectionsApi.
 * @export
 * @interface SectionsApiGetSpecificSectionRequest
 */
export type SectionsApiGetSpecificSectionRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetSpecificSection
    */
    readonly id: string
    
}

/**
 * Request parameters for getTerm operation in SectionsApi.
 * @export
 * @interface SectionsApiGetTermRequest
 */
export type SectionsApiGetTermRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetTerm
    */
    readonly id: string
    
}

/**
 * Request parameters for getUsers operation in SectionsApi.
 * @export
 * @interface SectionsApiGetUsersRequest
 */
export type SectionsApiGetUsersRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetUsers
    */
    readonly id: string
    
    /**
    * 
    * @type {'student' | 'teacher'}
    * @memberof SectionsApiGetUsers
    */
    readonly role?: 'student' | 'teacher'
    
    /**
    * 
    * @type {number}
    * @memberof SectionsApiGetUsers
    */
    readonly limit?: number
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetUsers
    */
    readonly startingAfter?: string
    
    /**
    * 
    * @type {string}
    * @memberof SectionsApiGetUsers
    */
    readonly endingBefore?: string
    
}

/**
 * SectionsApiGenerated - object-oriented interface
 * @export
 * @class SectionsApiGenerated
 * @extends {BaseAPI}
 */
export class SectionsApiGenerated extends BaseAPI {
    /**
     * Returns the course for a section
     * @param {SectionsApiGetCourseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getCourse(requestParameters: SectionsApiGetCourseRequest, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getCourse(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the district for a section
     * @param {SectionsApiGetDistrictRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getDistrict(requestParameters: SectionsApiGetDistrictRequest, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getDistrict(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of sections
     * @param {SectionsApiGetListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getList(requestParameters: SectionsApiGetListRequest = {}, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getList(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the resources for a section
     * @param {SectionsApiGetResourcesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getResources(requestParameters: SectionsApiGetResourcesRequest, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getResources(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the school for a section
     * @param {SectionsApiGetSchoolRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getSchool(requestParameters: SectionsApiGetSchoolRequest, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getSchool(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a specific section
     * @param {SectionsApiGetSpecificSectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getSpecificSection(requestParameters: SectionsApiGetSpecificSectionRequest, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getSpecificSection(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the term for a section
     * @param {SectionsApiGetTermRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getTerm(requestParameters: SectionsApiGetTermRequest, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getTerm(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the student and/or teacher users for a section
     * @param {SectionsApiGetUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SectionsApiGenerated
     */
    public getUsers(requestParameters: SectionsApiGetUsersRequest, options?: AxiosRequestConfig) {
        return SectionsApiFp(this.configuration).getUsers(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
