/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { StudentRelationship } from './student-relationship';

/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'legacy_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'phone_type'?: ContactPhoneTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'sis_id'?: string | null;
    /**
     * 
     * @type {Array<StudentRelationship>}
     * @memberof Contact
     */
    'student_relationships'?: Array<StudentRelationship>;
}

type ContactPhoneTypeEnum = 'Cell' | 'Home' | 'Work' | 'Other' | ''


