/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CourseResponse } from './course-response';
import { Link } from './link';

/**
 * 
 * @export
 * @interface CoursesResponse
 */
export interface CoursesResponse {
    /**
     * 
     * @type {Array<CourseResponse>}
     * @memberof CoursesResponse
     */
    'data'?: Array<CourseResponse>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof CoursesResponse
     */
    'links'?: Array<Link>;
}

