/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DistrictContact } from './district-contact';

/**
 * 
 * @export
 * @interface District
 */
export interface District {
    /**
     * 
     * @type {DistrictContact}
     * @memberof District
     */
    'district_contact'?: DistrictContact;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'last_sync'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'launch_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'lms_state'?: DistrictLmsStateEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof District
     */
    'login_methods'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'mdr_number'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'nces_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'pause_end'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'pause_start'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'portal_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'sis_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    'state'?: DistrictStateEnum;
}

type DistrictLmsStateEnum = 'matching_in_progress' | 'error' | 'disconnected' | '' | 'success'
type DistrictStateEnum = 'running' | 'pending' | 'error' | 'paused' | '' | 'success'


