/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DistrictAdmin
 */
export interface DistrictAdmin {
    /**
     * 
     * @type {string}
     * @memberof DistrictAdmin
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DistrictAdmin
     */
    'legacy_id'?: string;
}

