/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InternalError
 */
export interface InternalError {
    /**
     * 
     * @type {string}
     * @memberof InternalError
     */
    'message'?: string;
}

