/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    'rel'?: LinkRelEnum;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    'uri'?: string;
}

type LinkRelEnum = 'next' | 'prev' | 'self'


