/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'lat'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'lon'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'state'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'zip'?: string | null;
}

