/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Name
 */
export interface Name {
    /**
     * 
     * @type {string}
     * @memberof Name
     */
    'first'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Name
     */
    'last'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Name
     */
    'middle'?: string | null;
}

