/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Resource
 */
export interface Resource {
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    'district'?: string;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    'resource_id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Resource
     */
    'roles'?: Array<ResourceRolesEnum>;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    'updated'?: string;
}

type ResourceRolesEnum = 'teacher' | 'student'


