/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { ResourceResponse } from './resource-response';

/**
 * 
 * @export
 * @interface ResourcesResponse
 */
export interface ResourcesResponse {
    /**
     * 
     * @type {Array<ResourceResponse>}
     * @memberof ResourcesResponse
     */
    'data'?: Array<ResourceResponse>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof ResourcesResponse
     */
    'links'?: Array<Link>;
}

