/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SchoolEnrollment
 */
export interface SchoolEnrollment {
    /**
     * 
     * @type {string}
     * @memberof SchoolEnrollment
     */
    'end_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof SchoolEnrollment
     */
    'school'?: string;
    /**
     * 
     * @type {string}
     * @memberof SchoolEnrollment
     */
    'start_date'?: string;
}

