/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Section
 */
export interface Section {
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'course'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'district'?: string;
    /**
     * 
     * @type {object}
     * @memberof Section
     */
    'ext'?: object;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'grade'?: SectionGradeEnum;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'last_modified'?: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'period'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'school'?: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'section_number'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'sis_id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Section
     */
    'students'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'subject'?: SectionSubjectEnum;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'teacher'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Section
     */
    'teachers'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    'term_id'?: string | null;
}

type SectionGradeEnum = 'InfantToddler' | 'Preschool' | 'PreKindergarten' | 'TransitionalKindergarten' | 'Kindergarten' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12' | '13' | 'PostGraduate' | 'Ungraded' | 'Other' | ''
type SectionSubjectEnum = 'english/language arts' | 'math' | 'science' | 'social studies' | 'language' | 'homeroom/advisory' | 'interventions/online learning' | 'technology and engineering' | 'PE and health' | 'arts and music' | 'other' | ''


