/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { SectionResponse } from './section-response';

/**
 * 
 * @export
 * @interface SectionsResponse
 */
export interface SectionsResponse {
    /**
     * 
     * @type {Array<SectionResponse>}
     * @memberof SectionsResponse
     */
    'data'?: Array<SectionResponse>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof SectionsResponse
     */
    'links'?: Array<Link>;
}

