/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StudentRelationship
 */
export interface StudentRelationship {
    /**
     * 
     * @type {string}
     * @memberof StudentRelationship
     */
    'relationship'?: StudentRelationshipRelationshipEnum;
    /**
     * 
     * @type {string}
     * @memberof StudentRelationship
     */
    'student'?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentRelationship
     */
    'type'?: StudentRelationshipTypeEnum;
}

type StudentRelationshipRelationshipEnum = 'Parent' | 'Grandparent' | 'Self' | 'Aunt/Uncle' | 'Sibling' | 'Other' | ''
type StudentRelationshipTypeEnum = 'Parent/Guardian' | 'Emergency' | 'Primary' | 'Secondary' | 'Family' | 'Other' | ''


