/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Credentials } from './credentials';
import { Name } from './name';

/**
 * 
 * @export
 * @interface Teacher
 */
export interface Teacher {
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'created'?: string;
    /**
     * 
     * @type {Credentials}
     * @memberof Teacher
     */
    'credentials'?: Credentials;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'district'?: string;
    /**
     * 
     * @type {object}
     * @memberof Teacher
     */
    'ext'?: object;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'last_modified'?: string;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'legacy_id'?: string;
    /**
     * 
     * @type {Name}
     * @memberof Teacher
     */
    'name'?: Name;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'school'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Teacher
     */
    'schools'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'sis_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'state_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Teacher
     */
    'teacher_number'?: string | null;
}

