/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Link } from './link';
import { TermResponse } from './term-response';

/**
 * 
 * @export
 * @interface TermsResponse
 */
export interface TermsResponse {
    /**
     * 
     * @type {Array<TermResponse>}
     * @memberof TermsResponse
     */
    'data'?: Array<TermResponse>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof TermsResponse
     */
    'links'?: Array<Link>;
}

