/*
Data API

Serves the Clever Data API

The version of the OpenAPI document: 3.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Name } from './name';
import { Roles } from './roles';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'district'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_modified'?: string;
    /**
     * 
     * @type {Name}
     * @memberof User
     */
    'name'?: Name;
    /**
     * 
     * @type {Roles}
     * @memberof User
     */
    'roles'?: Roles;
}

